DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS message_mark;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS group_member;
DROP TABLE IF EXISTS room_friend;
DROP TABLE IF EXISTS room_group;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS user;
