CREATE TABLE user (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL,
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE room (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type TINYINT NOT NULL,
  hot_flag TINYINT NOT NULL DEFAULT 0,
  active_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_msg_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE room_group (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  delete_status TINYINT NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_room_id (room_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE room_friend (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  uid1 BIGINT UNSIGNED NOT NULL,
  uid2 BIGINT UNSIGNED NOT NULL,
  UNIQUE KEY uk_room_id (room_id),
  KEY idx_uid1_uid2 (uid1, uid2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE group_member (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  group_id BIGINT UNSIGNED NOT NULL,
  uid BIGINT UNSIGNED NOT NULL,
  role TINYINT NOT NULL DEFAULT 3,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_group_uid (group_id, uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE message (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_id BIGINT UNSIGNED NOT NULL,
  from_uid BIGINT UNSIGNED NOT NULL,
  content TEXT NOT NULL,
  type TINYINT NOT NULL,
  reply_msg_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 0,
  extra JSON NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_room_id_id (room_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE message_mark (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  msg_id BIGINT UNSIGNED NOT NULL,
  uid BIGINT UNSIGNED NOT NULL,
  type TINYINT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_msg_uid_type (msg_id, uid, type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE contact (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  uid BIGINT UNSIGNED NOT NULL,
  room_id BIGINT UNSIGNED NOT NULL,
  active_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  unread_count INT NOT NULL DEFAULT 0,
  UNIQUE KEY uk_uid_room (uid, room_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
